design_name = "sparse_prefix_sum"
dataset_name = "xls_upstream"
tags = ["scan", "array", "dslx", "upstream"]

[[flow_configs]]
flow_name = "XLSHLSSynthFlow"
dslx_file = "sparse_prefix_sum.x"
top = "sparse_prefix_sum"
generator = "pipeline"
pipeline_stages = "1"
delay_model = "unit"
