design_name = "fp_sincos_32"
dataset_name = "xls_upstream"
tags = ["floating-point", "trig", "dslx", "upstream"]

[[flow_configs]]
flow_name = "XLSHLSSynthFlow"
dslx_file = "fp_sincos_32.x"
top = "fp_sincos_32"
generator = "pipeline"
pipeline_stages = "1"
delay_model = "unit"
dslx_path = "."
