design_name = "fpsqrt_32"
dataset_name = "xls_upstream"
tags = ["floating-point", "sqrt", "dslx", "upstream"]

[[flow_configs]]
flow_name = "XLSHLSSynthFlow"
dslx_file = "fpsqrt_32.x"
top = "fpsqrt_32"
generator = "pipeline"
pipeline_stages = "1"
delay_model = "unit"
