design_name = "adder"
dataset_name = "test_designs_xls"
tags = ["test", "arithmetic", "dslx"]

[[flow_configs]]
flow_name = "XLSHLSSynthFlow"
dslx_file = "adder.x"
top = "add"
generator = "pipeline"
pipeline_stages = "1"
delay_model = "unit"
